// session
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const RESET_SESSION = 'RESET_SESSION';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

// targets
export const CREATE_TARGET = 'CREATE_TARGET';
export const LOAD_TARGETS = 'LOAD_TARGETS';
export const UPDATE_TARGET = 'UPDATE_TARGET';
export const DELETE_TARGET = 'DELETE_TARGET';
export const RESET_TARGETS = 'RESET_TARGETS';
export const UPDATE_FREE_TARGET = 'UPDATE_FREE_TARGET';
export const RESET_FREE_TARGET = 'RESET_FREE_TARGET';
export const UPDATE_SELECTED_TARGET = 'UPDATE_SELECTED_TARGET';
export const UPDATE_SELECTED_TARGET_FIELD = 'UPDATE_SELECTED_TARGET_FIELD';
export const RESET_SELECTED_TARGET = 'RESET_SELECTED_TARGET';

// alerts
export const CREATE_ALERT = 'CREATE_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

// topics
export const LOAD_TOPICS = 'LOAD_TOPICS';

// matches
export const LOAD_MATCHES = 'LOAD_MATCHES';

// messages
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

// sidebar content
export const SWITCH_CONTENT = 'SWITCH_CONTENT';

// new conversation
export const UPDATE_CURRENT_CONVERSATION = 'UPDATE_CURRENT_CONVERSATION';
export const CLOSE_CURRENT_CONVERSATION = 'CLOSE_CURRENT_CONVERSATION';
